apiVersion: apps/v1
kind: Deployment

metadata:
  name: internship-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: internship-app

  template:
    metadata:
      labels:
        app: internship-app

    spec:
      containers:
        - name: internship-app
          image: dhairya2704/internship-app:latest

          ports:
            - containerPort: 3000

          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
