apiVersion: apps/v1
kind: Deployment

metadata:
  name: internship-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: internship-app

  template:
    metadata:
      labels:
        app: internship-app

    spec:
      automountServiceAccountToken: false

      containers:
        - name: internship-app
          image: dhairya2704/internship-app:v1

          ports:
            - containerPort: 3000

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
              ephemeral-storage: "1Gi"

            limits:
              memory: "256Mi"
              cpu: "200m"
              ephemeral-storage: "2Gi"
