apiVersion: v1
kind: Service

metadata:
  name: internship-service

spec:
  type: NodePort

  selector:
    app: internship-app

  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
